# Generated by Django 2.2.7 on 2020-07-23 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Traffic',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('id', models.AutoField(help_text='id主键', primary_key=True, serialize=False, verbose_name='id主键')),
                ('serialnumber', models.CharField(help_text='任务号', max_length=30)),
                ('urls', models.CharField(help_text='背景图地址', max_length=30)),
                ('params', models.TextField(help_text='具体参数', max_length=5000)),
                ('Accuracy', models.FloatField(help_text='准确率')),
                ('plate_number', models.CharField(help_text='车牌号码', max_length=20)),
            ],
            options={
                'verbose_name': '车辆信息',
                'verbose_name_plural': '车辆信息',
                'db_table': 'tb_traffic',
            },
        ),
    ]
